[package]
name = "ora"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30"
wgpu = "23"
generational-arena = "0.2"
pollster = "0.4"
log = "0.4"
bytemuck = { version = "1", features = ["derive"] }
glyphon = "0.7"
async-executor = "1"
image = "0.24"
lru = "0.12"
core_editor = { path = "../core_editor" }

[dev-dependencies]
env_logger = "0.11"
